language: node_js
node_js:
  - "node"
  - "lts/*"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
sudo: false
addons:
  code_climate:
    repo_token: cbaad853d2d044392284a92dd597b18d5bf92418859dbb5e6ebafaa903c972cf
script: "npm run coverage"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
